'From Cuis 5.0 [latest update: #4963] on 24 November 2021 at 5:57:20 pm'!
'Description '!
!provides: 'GWJ-Package' 1 0!
SystemOrganization addCategory: 'GWJ-Package'!


!classDefinition: #IEDict category: 'GWJ-Package'!
Object subclass: #IEDict
	instanceVariableNames: ''
	classVariableNames: 'DictData'
	poolDictionaries: ''
	category: 'GWJ-Package'!
!classDefinition: 'IEDict class' category: 'GWJ-Package'!
IEDict class
	instanceVariableNames: ''!


!IEDict commentStamp: '<historical>' prior: 0!
Junk you can remove, this was a first tutorials!
